export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  SCAN: '/scan',
  WALLETS: '/wallets',
  TRANSACTIONS: '/transactions',
  BUDGETS: '/budgets',
  GOALS: '/goals',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  CATEGORIES: '/categories',
  RECURRING_INCOMES: '/recurring',
  RECURRING_RULES: '/recurring-rules',
}

export const QUERY_KEYS = {
  WALLETS: 'wallets',
  CATEGORIES: 'categories',
  TRANSACTIONS: 'transactions',
  BUDGETS: 'budgets',
  GOALS: 'goals',
  DASHBOARD: 'dashboard',
  ME: 'me',
  RECURRING_INCOMES: 'recurring-incomes',
  RECURRING_SUGGESTIONS: 'recurring-suggestions',
  RECURRING_RULES: 'recurring-rules',
  NOTIFICATIONS: 'notifications',
}

export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
  },
  WALLETS: '/wallets',
  CATEGORIES: '/categories',
  TRANSACTIONS: '/transactions',
  BUDGETS: '/budgets',
  GOALS: '/goals',
  DASHBOARD: '/dashboard',
  OCR: '/ocr',
  RECURRING_INCOMES: '/recurring-incomes',
  RECURRING: '/recurring',
  NOTIFICATIONS: '/notifications',
}